vars: {
  d2-config: {
    layout-engine: elk
  }
}

direction: right

classes: {
  func: {
    shape: rectangle
    style: {
      fill: "#BDFB9B"
      stroke: "#166534"
      stroke-width: 2
      font-size: 36
    }
  }
  sys: {
    style: {
      fill: "#E6E6E6"
      stroke: "#9A9A9A"
      stroke-width: 2
      font-size: 48
    }
  }
  ea: {
    shape: rectangle
    style: {
      fill: "#BFEAF4"
      stroke: "#5B65C9"
      stroke-width: 2
      border-radius: 20
      font-size: 40
    }
  }
  note: {
    style: {
      fill: "#FFF5B0"
      stroke: "#D1B24A"
      font-size: 32
    }
  }
  chain: {
    style: {
      fill: "#FFFFFF"
      stroke: "#D1B24A"
      stroke-width: 2
      border-radius: 20
      font-size: 36
    }
  }
  fe: {
    style: {
      stroke: "#1F7A4D"
      font-color: "#1F7A4D"
      stroke-width: 2
      font-size: 30
    }
  }
  cstr: {
    style: {
      stroke: "#333333"
      stroke-dash: 3
      font-size: 26
    }
  }
}

alert_insufficient_supply: "Functional Chain — Alert insufficient supply" {
  class: chain
  direction: right

  measure_volume: "[F] Measure water\nvolume" {
    class: func
    shape: rectangle
  }
  measure_flow: "[F] Measure current\nflow" {
    class: func
    shape: rectangle
  }
  measure_level: "[F] Measure water\nlevel" {
    class: func
    shape: rectangle
  }
  collect_sd: "[F] Collect S/D\nmeasurements" {
    class: func
    shape: rectangle
  }
  notify_is_event: "[F] Notify of insufficient\nsupply events" {
    class: func
    shape: rectangle
  }
  predict_sd: "[F] Predict water supply\nand demand" {
    class: func
    shape: rectangle
  }
  notify_is_risk: "[F] Notify of high insufficient\nsupply probability" {
    class: func
    shape: rectangle
  }
  define_rules: "[F] Define water\ndistribution rules" {
    class: func
    shape: rectangle
  }


  measure_volume -> collect_sd: "[FE] Water volume" {
    class: fe
  }
  measure_flow -> collect_sd: "[FE] Current flow" {
    class: fe
  }
  measure_level -> collect_sd: "[FE] Water level" {
    class: fe
  }
  collect_sd -> notify_is_event: "[FE] S/D measurements" {
    class: fe
  }
  notify_is_event -> define_rules: "[FE] Insufficient supply\nevent" {
    class: fe
  }
  collect_sd -> predict_sd: "[FE] S/D measurements" {
    class: fe
  }
  predict_sd -> notify_is_risk: "[FE] S/D predictions" {
    class: fe
  }
  notify_is_risk -> define_rules: "[FE] High insufficient supply\nprobability" {
    class: fe
  }

}
