vars: {
  d2-config: {
    layout-engine: elk
  }
}

direction: right
grid-columns: 5

classes: {
  func: {
    shape: rectangle
    style: {
      fill: "#BDFB9B"
      stroke: "#166534"
      stroke-width: 2
      font-size: 36
    }
  }
  sys: {
    style: {
      fill: "#E6E6E6"
      stroke: "#9A9A9A"
      stroke-width: 2
      font-size: 48
    }
  }
  ea: {
    shape: rectangle
    style: {
      fill: "#BFEAF4"
      stroke: "#5B65C9"
      stroke-width: 2
      border-radius: 20
      font-size: 40
    }
  }
  note: {
    style: {
      fill: "#FFF5B0"
      stroke: "#D1B24A"
      font-size: 32
    }
  }
  chain: {
    style: {
      fill: "#FFFFFF"
      stroke: "#D1B24A"
      stroke-width: 2
      border-radius: 20
      font-size: 36
    }
  }
  fe: {
    style: {
      stroke: "#1F7A4D"
      font-color: "#1F7A4D"
      stroke-width: 2
      font-size: 30
    }
  }
  cstr: {
    style: {
      stroke: "#333333"
      stroke-dash: 3
      font-size: 26
    }
  }
}

octave_meter: "[EA] Octave Water Meter" {
  class: ea
  shape: rectangle
  direction: down
  grid-columns: 1

  measure_volume: "[F] Measure water\nvolume" {
    class: func
    shape: rectangle
  }
  measure_flow: "[F] Measure current\nflow" {
    class: func
    shape: rectangle
  }
}

level_sensor: "[EA] Submersible water\nlevel sensor" {
  class: ea
  shape: rectangle
  direction: down
  grid-columns: 1

  measure_level: "[F] Measure water\nlevel" {
    class: func
    shape: rectangle
  }
}

system: "[System] Aqueduct monitoring,\nalerting, and data sharing system" {
  class: sys
  direction: right
  grid-columns: 4

  collect_sd: "[F] Collect S/D\nmeasurements" {
    class: func
    shape: rectangle
  }
  c_collect: "[C] Real-time and remote" {
    class: note
    shape: page
  }
  quantify_wl: "[F] Quantify\nwater loss" {
    class: func
    shape: rectangle
  }
  c_quantify: "[C] Detect discrete events\n(overflow, pipe burst)" {
    class: note
    shape: page
  }

  predict_sd: "[F] Predict water supply\nand demand" {
    class: func
    shape: rectangle
  }
  predict_wl_risk: "[F] Predict water loss\nevent risk" {
    class: func
    shape: rectangle
  }
  notify_wl_event: "[F] Notify of significant\nwater loss events" {
    class: func
    shape: rectangle
  }
  notify_wl_risk: "[F] Notify of high water loss\nevent probability" {
    class: func
    shape: rectangle
  }

  notify_is_event: "[F] Notify of insufficient\nsupply events" {
    class: func
    shape: rectangle
  }
  notify_is_risk: "[F] Notify of high insufficient\nsupply probability" {
    class: func
    shape: rectangle
  }
  store_data: "[F] Store measurements\nand events" {
    class: func
    shape: rectangle
  }
  c_store: "[C] Timestamped" {
    class: note
    shape: page
  }

  present_data: "[F] Present stored\ndata" {
    class: func
    shape: rectangle
  }
  c_present: "[C] Time series graphs\nFiltered" {
    class: note
    shape: page
  }
  share_external: "[F] Make data accessible\nto external entities" {
    class: func
    shape: rectangle
  }

  c_collect -> collect_sd: {
    class: cstr
  }
  c_quantify -> quantify_wl: {
    class: cstr
  }
  c_store -> store_data: {
    class: cstr
  }
  c_present -> present_data: {
    class: cstr
  }
}

employee: "[EA] ASADA Paso Ancho\nemployee" {
  class: ea
  shape: rectangle
  direction: down
  grid-columns: 2

  consult_wl: "[F] Consult water\nloss data" {
    class: func
    shape: rectangle
  }
  implement_mitigation: "[F] Implement water loss\nmitigation strategy" {
    class: func
    shape: rectangle
  }
  consult_sd: "[F] Consult S/D\ndata" {
    class: func
    shape: rectangle
  }
  define_rules: "[F] Define water\ndistribution rules" {
    class: func
    shape: rectangle
  }
  c_quality_vars: "[C] Monitor all Regulation\n38924-S required variables" {
    class: note
    shape: page
  }
  monitor_quality: "[F] Monitor\nwater quality" {
    class: func
    shape: rectangle
  }
  implement_quality_compliance: "[F] Implement water quality\nstandards compliance\nstrategy" {
    class: func
    shape: rectangle
  }

  c_quality_vars -> monitor_quality: {
    class: cstr
  }
}

external_aggs: "[EA] External data\naggregators" {
  class: ea
  shape: rectangle
  direction: down
  grid-columns: 1

  receive_data: "[F] Receive\naqueduct data" {
    class: func
    shape: rectangle
  }
}

octave_meter -> level_sensor: {
  style: {
    opacity: 0
  }
}
level_sensor -> system: {
  style: {
    opacity: 0
  }
}
system -> employee: {
  style: {
    opacity: 0
  }
}
employee -> external_aggs: {
  style: {
    opacity: 0
  }
}
